###
GET http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "felix",
    "surname": "hola",
    "email": "prueba@",
    "password": "prueba"
}
###
GET http://localhost:3000/api/users/1
